import React from 'react';
import ImageSlider from './ImageSlider';
import NavigationPoints from './NavigationPoints';

const Home = () => {
    return (
        <div className="portfolio-container">
            <ImageSlider />
            <NavigationPoints />
            <p className="portfolio-intro">Welcome to my portfolio page for the Exercise Tracker 
            Application I've built using React!</p>

            <div id="about" className="section">
                <h2>About the Project</h2>
                <p>
                    The Exercise Tracker Application is a web-based solution designed to help users track
                    their exercise routines. It allows users to log their exercise.
                </p>
            </div>

            <div id="features" className="section">
                <h2>Key Features</h2>
                <ul>
                    <li>User authentication and registration.</li>
                    <li>Exercise logging with details like exercise type, duration, description and date.</li>
                </ul>
            </div>

            <div id="technologies" className="section">
                <h2>Technologies Used</h2>
                <p>
                    This application was built using modern web development technologies:
                </p>
                <ul>
                    <li>React for building the user interface.</li>
                    <li>React Router for handling navigation.</li>
                    <li>Node.js and Express.js for the backend server.</li>
                    <li>MongoDB for data storage.</li>
                    <li>Bootstrap & CSS for styling.</li>
                    <li>JWT for authentication.</li>
                </ul>
            </div>

            <div id="future" className="section">
                <h2>Future Enhancements</h2>
                <p>
                    I'm continually working to improve the application and plan to add new features in 
                    the future, such as:
                </p>
                <ul>
                    <li>Integration with fitness wearables and APIs.</li>
                    <li>Social sharing capabilities.</li>
                    <li>Personalized workout plans generated by AI.</li>
                </ul>
            </div>

            <div id="checkitout" className="section">
                <h2>Check It Out</h2>
                <p>
                    If you're interested in using the Exercise Tracker Application or exploring its code, 
                    feel free to visit the GitHub repository: 
                    <a href="https://github.com/umer-shehzad/Exercise-Tracker-MERN-APP" 
                    target="_blank" 
                    rel="noopener noreferrer">Exercise Tracker GitHub Repository
                    </a>.
                </p>
            </div>
        </div>
    );
};

export default Home;
